name: Deploy to Cloudflare Pages

on:
    push:
        branches: [main, master]
    workflow_dispatch:

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            deployments: write
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Use Node 20
              uses: actions/setup-node@v4
              with:
                  node-version: "20"
                  cache: "npm"

            - name: Install root deps
              run: npm install --no-audit --no-fund --progress=false

            - name: Build webview-ui
              run: npm run build

            - name: Install Wrangler
              run: npm install --no-audit --no-fund --progress=false --global wrangler@^3

            - name: Publish to Cloudflare Pages
              env:
                  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
              run: |
                  wrangler pages deploy webview-ui/build \
                    --project-name=cline-webview-ui \
                    --branch=${{ github.ref_name }}
